CREATE TYPE role_type AS ENUM('USER', 'ADMIN');

CREATE TABLE IF NOT EXISTS
  people (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    roles role_type[] NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
  );

